project_name: talkingheads

pre_window: gvm use go1.22.4

windows:
  - main:
      layout: main-horizontal
      panes:
        - moderator:
          - cd ./cmd
          - go run ./moderator/ -server="localhost:1883"
        - llama:
          - cd ./cmd
          - go run ./panelist/ -l="en-US" -voice="joe-medium" -data="../voices" -tts-engine="piper" -gpu=true -model="Lexi-Llama-3-8B-Uncensored_Q4_K_M" -name="llama" -server="localhost:1883"
        - phi:
          - cd ./cmd
          - go run ./panelist/ -l="en-US" -voice="hfc_male-medium" -data="../voices" -tts-engine="piper" -gpu=true -model="Phi-3-mini-128k-instruct-abliterated-v3_q4" -name="phi" -server="localhost:1883"
        - qwen:
          - cd ./cmd
          - go run ./panelist/ -l="en-US" -voice="john-medium" -data="../voices" -tts-engine="piper" -gpu=true -model="rjmalagon/dolphin-2.9.3-qwen2-1.5b-f16" -name="qwen" -server="localhost:1883"
